# 과제 목표

파이썬 numpy 패키지를 이용해 주어진 행렬에 대한 QR 분해를 구하는 코드를 작성합니다.

참고자료: [링크](https://numpy.org/doc/stable/reference/generated/numpy.linalg.qr.html)

## 행렬 $A$ 정의

다음의 3x3 행렬 $A$를 정의하는 numpy 코드를 작성하시오.

$$ A = 
\left[
\begin{array}{rrr}
 3 &  1 &  1 \\
 1 & -2 & -1 \\
 1 &  1 &  1
\end{array}
\right]
$$

In [ ]:
import numpy as np
import numpy.linalg 

In [ ]:
# 행렬 코딩
A = np.array([[3,1,1],[1,-2,-1],[1,1,1]])

print(A)
print(np.shape(A))

[[ 3  1  1]
 [ 1 -2 -1]
 [ 1  1  1]]
(3, 3)


## 행렬 $A$의 QR 분해 계산
앞서 정의한 행렬 $A$에 대해 LU 분해, $A = QR$를 수행하는 numpy 코드를 작성하시오.

In [ ]:
# QR 분해
Q, R = np.linalg.qr(A)

print("Q:", Q)
print("R:", R)

## QR 분해 결과 체크: 연산결과가 A와 동일한지 체크
AA = Q@R
print("AA:", AA)

Q: [[-0.90453403  0.1914599  -0.38100038]
 [-0.30151134 -0.9190075   0.25400025]
 [-0.30151134  0.34462781  0.88900089]]
R: [[-3.31662479 -0.60302269 -0.90453403]
 [ 0.          2.3741027   1.4550952 ]
 [ 0.          0.          0.25400025]]
AA: [[ 3.  1.  1.]
 [ 1. -2. -1.]
 [ 1.  1.  1.]]


## 벡터 정의
다음의 3-벡터 $\mathbf{b}$를 정의하는 numpy 코드를 작성하시오.
$$ \mathbf{b} = 
\left[
\begin{array}{rrr}
 4 \\
 1 \\
 2
\end{array}
\right]
$$

In [ ]:
# 벡터 코딩
b = np.array([4,1,2])

print(b)
print(np.shape(b))

[4 1 2]
(3,)


## QR-분해를 이용해 선형시스템 $A \mathbf{x} = \mathbf{b}$ 풀기
행렬 $A$에 대한 QR 분해를 이용해 $A\mathbf{x} = \mathbf{b}$를 계산하는 numpy 코드를 작성하시오.

$A \mathbf{x} = \mathbf{b}$를 $QR \mathbf{x} = \mathbf{b}$ 문제로 본 후, 다음을 해결한다.
- $R \mathbf{x} = \mathbf{y}$로 설정하고, $Q \mathbf{y} = \mathbf{b}$ 문제를 풀어 $\mathbf{y}$를 얻는다.
- $R \mathbf{x} = \mathbf{y}$ 문제를 풀어 $\mathbf{x}$를 얻는다.

### 선형시스템 $Q\mathbf{y} = \mathbf{b}$ 풀기

$Q$는 정규직교행렬(orthonormal matrix)이므로 $Q$의 역행렬은 전치행렬인 $Q^{T}$와 같습니다. 

이러한 성질을 이용해 $\mathbf{y}$를 구하는 numpy 코드를 작성하세요.

In [ ]:
# Qy = b 풀기

y = Q.T@b


print("y:", y)
print(np.shape(y))

y: [-4.52267017  0.53608771  0.50800051]
(3,)


## 선형시스템 $R \mathbf{x} = \mathbf{y}$ 풀기

$R$은 역행렬이 존재하는 상삼각행렬(upper triangular matrix)입니다. 

이러한 성질을 이용해 $\mathbf{x}$를 구하는 numpy 코드를 작성하세요.

In [ ]:
# Rx = y 풀기

x = np.linalg.inv(R)@y

print("x:", x)
print(np.shape(x))

x: [ 1. -1.  2.]
(3,)


## 선형시스템의 해 확인

앞서 QR 분해를 이용해 구한 $\mathbf{x}$가 선형시스템 $A\mathbf{x} = \mathbf{b}$의 해(solution)로서 알맞게 구한 것인지 검증하는 코드를 작성하시오.

In [ ]:
## 결과 검증

bb = A@x

if np.allclose(b, bb):
  print("Ok")
else:
  print("something wrong")

Ok
