# 과제 목표

파이썬 numpy, scipy 패키지를 이용해 주어진 행렬에 대한 LU 분해를 구하는 코드를 작성합니다.

참고자료: [링크](https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.lu.html)

## 행렬 $A$ 정의

다음의 3x3 행렬 $A$를 정의하는 numpy 코드를 작성하시오.

$$ A = 
\left[
\begin{array}{rrr}
 3 &  1 &  1 \\
 1 & -2 & -1 \\
 1 &  1 &  1
\end{array}
\right]
$$

In [ ]:
import numpy as np
import scipy.linalg 

In [ ]:
# 행렬 코딩

## TODO
A = np.array([[3,1,1],[1,-2,-1],[1,1,1]])

print(A)
print(np.shape(A))

[[ 3  1  1]
 [ 1 -2 -1]
 [ 1  1  1]]
(3, 3)


## 행렬 $A$의 LU 분해 계산
앞서 정의한 행렬 $A$에 대해 LU 분해, $A = PLU$를 수행하는 scipy 코드를 작성하시오.

In [ ]:
# PLU 분해

## TODO
P, L, U = scipy.linalg.lu(A)

print("P:", P)
print("L:", L)
print("U:", U)

AA = P @ L @ U
print("AA:", AA)

P: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
L: [[ 1.          0.          0.        ]
 [ 0.33333333  1.          0.        ]
 [ 0.33333333 -0.28571429  1.        ]]
U: [[ 3.          1.          1.        ]
 [ 0.         -2.33333333 -1.33333333]
 [ 0.          0.          0.28571429]]
AA: [[ 3.  1.  1.]
 [ 1. -2. -1.]
 [ 1.  1.  1.]]


## 벡터 정의
다음의 3-벡터 $\mathbf{b}$를 정의하는 numpy 코드를 작성하시오.
$$ \mathbf{b} = 
\left[
\begin{array}{rrr}
 4 \\
 1 \\
 2
\end{array}
\right]
$$

In [ ]:
# 벡터 코딩

## TODO
b = np.array([4,1,2])

print(b)
print(np.shape(b))

[4 1 2]
(3,)


## LU-분해를 이용해 선형시스템 $A \mathbf{x} = \mathbf{b}$ 풀기
행렬 $A$에 대한 LU 분해를 이용해 $A\mathbf{x} = \mathbf{b}$를 계산하는 scipy 코드를 작성하시오.

In [ ]:
# LU 분해

## TODO
lu, piv = scipy.linalg.lu_factor(A)
x = scipy.linalg.lu_solve((lu, piv), b)

print("x:", x)
print(np.shape(x))

x: [ 1. -1.  2.]
(3,)


## 선형시스템의 해 확인

앞서 LU 분해를 이용해 구한 $\mathbf{x}$가 선형시스템 $A\mathbf{x} = \mathbf{b}$의 해(solution)로서 알맞게 구한 것인지 검증하는 코드를 작성하시오.

방법: $A\mathbf{x}$의 연산결과가 $\mathbf{b}$와 충분히 가까운지를 검증한다. [참고자료: [링크](https://numpy.org/doc/stable/reference/generated/numpy.allclose.html)]

In [ ]:
## 결과 검증

# TODO
bb = A @ x

if np.allclose(b, bb):
  print("Ok")
else:
  print("something wrong")

Ok
