# 과제 목표

파이썬 numpy 패키지를 이용해 주어진 행렬의 랭크(rank)를 구하는 코드를 작성합니다.

참고자료: [링크](https://numpy.org/doc/stable/reference/generated/numpy.linalg.matrix_rank.html)

## 행렬 $A$ 정의

다음의 3x3 행렬 $A$를 정의하는 numpy 코드를 작성하시오.

$$ A = 
\left[
\begin{array}{rrr}
 1 &  2 &  1 \\
 1 &  2 &  3 \\
 2 &  3 & -1
\end{array}
\right]
$$

In [ ]:
import numpy as np

In [ ]:
# 행렬 코딩

## TODO
A = np.array([[1,2,1],[1,2,3],[2,3,-1]])

print(A)
print(np.shape(A))

[[ 1  2  1]
 [ 1  2  3]
 [ 2  3 -1]]
(3, 3)


## 행렬 $A$의 랭크 계산
앞서 정의한 행렬 $A$의 랭크(rank)를 계산하는 numpy 코드를 작성하시오.

In [ ]:
# 랭크 계산

## TODO
from numpy.linalg import matrix_rank
rank_A = matrix_rank(A)
print("rank(A): ", rank_A)

rank(A):  3


## 행렬 $B$ 정의

다음의 3x3 행렬 $B$를 정의하는 numpy 코드를 작성하시오.

$$ B = 
\left[
\begin{array}{rrr}
 1 &  2 &  1 \\
 1 &  2 &  3 \\
 2 &  4 &  4
\end{array}
\right]
$$

In [ ]:
# 행렬 코딩

## TODO
B = np.array([[1,2,3],[1,2,3],[2,4,4]])

print(B)
print(np.shape(B))

[[1 2 3]
 [1 2 3]
 [2 4 4]]
(3, 3)


## 행렬 $B$의 랭크 계산
앞서 정의한 행렬 $B$의 랭크(rank)를 계산하는 numpy 코드를 작성하시오.

In [ ]:
# 랭크 계산

## TODO
from numpy.linalg import matrix_rank
rank_B = matrix_rank(B)

print("rank(B): ", rank_B)

rank(B):  2


## 랭크의 의미 이해하기

거의 유사한 행렬 $A$와 $B$가 서로 다른 랭크가 나오는 것을 확인하였다. 특히, 행렬 $B$는 랭크가 3보다 적은 수로 나온다. 

행렬 $B$의 랭크가 3이 나오지 않는 그 이유를 설명하시오.

### [정답 작성란] B행렬을 전방소거법으로 풀이 하였을때 값을 가진 행의 갯수가 2개가 된다.  
