# 인공지능수학 선형대수 파트 기말 고사 2021년 1학기

- 2021년 6월 15일 23:59까지
- 이름 : 신용주
- 학번 : K2021022

선서: 본인은 이 과제를 수행함에 있어서 어떠한 부정행위도 없이
스스로의 힘으로 수행하였음을 선서합니다. 
- 서명: 신용주
  * (참고: 서명은 이름 작성으로 대신합니다.)


파이썬 numpy 패키지를 이용해, 아래 문제를 푸는 코드를 작성하고, 그 결과를 출력하세요. (배점: 각 문제당 25점씩)




# 문제 1)

다음의 4 x 4 행렬 $A$에 대해 물음에 답하라.

\begin{align*}
A &=
    \left[
    \begin{array}{rrrr}
     1 & -1 &  2 &  1 \\
    -1 &  2 &  0 & -2 \\
     1 &  1 &  7 & -3 \\
     1 & -3 & -1 &  2 \\
    \end{array}
    \right]
\end{align*}

(a) $A$의 역행렬 $A^{-1}$을 구하는 코드를 작성하시오.

(b) $A \mathbf{x} = \left[\begin{array}{r} 1 \\ -1 \\ 1 \\ -1 \end{array} \right]$를 만족하는 벡터 $\mathbf{x}$를 구하는 코드를 작성하시오.

In [ ]:
# [정답 작성란: 코드 셀을 추가로 만들어도 무방합니다.]
import numpy as np 
#(a)
A= np.array([[1,-1,2,1],[-1,2,0,-2],[1,1,7,-3],[1,-3,-1,2]])
A_inv= np.linalg.inv(A)
print(A_inv)
#(b)
Ax=np.array([1,-1,1,-1])
x= A_inv @ Ax

print(x)


[[-18. -23.   4.  -8.]
 [ -5.  -7.   1.  -3.]
 [  5.   6.  -1.   2.]
 [  4.   4.  -1.   1.]]
[17.  6. -4. -2.]


# 문제 2)

다음의 $5 \times 5$ 행렬 $A$에 대해 물음에 답하라.
\begin{align*}
A =
\left[
\begin{array}{rrrrr}
 1 &  2 &  0 &  1 &  2 \\
 2 &  6 &  0 &  0 &  4 \\
-3 & -2 & -1 & -8 & -8 \\
 2 &  0 & -2 &  5 &  3 \\
-1 &  0 &  1 & -1 &  5
\end{array}
\right]
\end{align*}


(a) 행렬 $A$의 $LDU$-분해를 구하라.

(b) $LDU$-분해 결과를 이용하여 $A\mathbf{x}_{i} = \mathbf{b}_{i}$의 해 $\mathbf{x}_{i}$를 각각 구하라 (단, $i=1, 2, 3$). 
        \begin{align*}
            \mathbf{b}_{1} = \left[ \begin{array}{r} 24 \\ 66 \\ -41 \\ 8 \\  9 \\ \end{array} \right], \quad
            \mathbf{b}_{2} = \left[ \begin{array}{r} 7 \\ 18 \\ -17 \\ 1 \\  6 \\ \end{array} \right], \quad 
            \mathbf{b}_{3} = \left[ \begin{array}{r} 21 \\ 46 \\ -78 \\ 10 \\ 42 \\ \end{array} \right].
        \end{align*}

In [ ]:
# [정답 작성란: 코드 셀을 추가로 만들어도 무방합니다.]
import numpy as np 
import scipy.linalg

A= np.array([[1,2,0,1,2],[2,6,0,0,4],[-3,-2,-1,-8,-8],[2,0,-2,5,3],[-1,0,1,-1,5]])
print(A)

(P,L,U)= scipy.linalg.lu(A)

print("P:", P)
print("L:", L)
print("U:", U)

D= np.diag(np.diag(U))
U /= np.diag(U)[:, None]
P.dot(L.dot(D.dot(U)))
print("D",D)


B1=np.array([24,66,-41,8,9])
B2=np.array([7,18,-17,1,6])
B3=np.array([21,46,-78,10,42])

lu, piv = scipy.linalg.lu_factor(A)
x1 = scipy.linalg.lu_solve((lu, piv), B1)

print("x1:", x1)

lu, piv = scipy.linalg.lu_factor(A)
x2 = scipy.linalg.lu_solve((lu, piv), B2)

print("x2:", x2)

lu, piv = scipy.linalg.lu_factor(A)
x3 = scipy.linalg.lu_solve((lu, piv), B3)

print("x3:", x3)


[[ 1  2  0  1  2]
 [ 2  6  0  0  4]
 [-3 -2 -1 -8 -8]
 [ 2  0 -2  5  3]
 [-1  0  1 -1  5]]
P: [[0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]
L: [[ 1.          0.          0.          0.          0.        ]
 [-0.66666667  1.          0.          0.          0.        ]
 [-0.66666667 -0.28571429  1.          0.          0.        ]
 [ 0.33333333  0.14285714 -0.5         1.          0.        ]
 [-0.33333333  0.28571429  0.05       -0.03333333  1.        ]]
U: [[-3.         -2.         -1.         -8.         -8.        ]
 [ 0.          4.66666667 -0.66666667 -5.33333333 -1.33333333]
 [ 0.          0.         -2.85714286 -1.85714286 -2.71428571]
 [ 0.          0.          0.          1.5         6.5       ]
 [ 0.          0.          0.          0.          0.06666667]]
D [[-3.          0.          0.          0.          0.        ]
 [ 0.          4.66666667  0.          0.          0.        ]
 [ 0.          0.         -2.85714286  0.        

# 문제 3)

다음의 선형시스템 $A\mathbf{x} = \mathbf{b}$에 대해 물음에 답하라.

\begin{align*}
A\mathbf{x} &= \mathbf{b} \\
\left[ \begin{array}{rrrrrrrrrrrr}
 1 & -1 & -1 & -1 & -1 & -1 & -1 & -1 & -1 & -1 & -1 & -1 \\
 1 &  1 & -1 &  1 & -1 & -1 & -1 &  1 &  1 &  1 & -1 &  1 \\
 1 &  1 &  1 & -1 &  1 & -1 & -1 & -1 &  1 &  1 &  1 & -1 \\
 1 & -1 &  1 &  1 & -1 &  1 & -1 & -1 & -1 &  1 &  1 &  1 \\
 1 &  1 & -1 &  1 &  1 & -1 &  1 & -1 & -1 & -1 &  1 &  1 \\
 1 &  1 &  1 & -1 &  1 &  1 & -1 &  1 & -1 & -1 & -1 &  1 \\
 1 &  1 &  1 &  1 & -1 &  1 &  1 & -1 &  1 & -1 & -1 & -1 \\
 1 & -1 &  1 &  1 &  1 & -1 &  1 &  1 & -1 &  1 & -1 & -1 \\
 1 & -1 & -1 &  1 &  1 &  1 & -1 &  1 &  1 & -1 &  1 & -1 \\
 1 & -1 & -1 & -1 &  1 &  1 &  1 & -1 &  1 &  1 & -1 &  1 \\
 1 &  1 & -1 & -1 & -1 &  1 &  1 &  1 & -1 &  1 &  1 & -1 \\
 1 & -1 &  1 & -1 & -1 & -1 &  1 &  1 &  1 & -1 &  1 &  1 \\
\end{array} \right]
\left[ \begin{array}{r}
x_{1} \\
x_{2} \\
x_{3} \\
x_{4} \\
x_{5} \\
x_{6} \\
x_{7} \\
x_{8} \\
x_{9} \\
x_{10} \\
x_{11} \\
x_{12} \\
\end{array} \right]
&=
\left[ \begin{array}{r}
-33 \\
 -5 \\
 19 \\
 -5 \\
 -9 \\
  7 \\
 11 \\
  9 \\
  5 \\
 11 \\
-23 \\
 13 \\
\end{array} \right]. \\
\end{align*}

(a) 행렬 $A$가 직교행렬(orthogonal matrix)인지 여부를 확인하는 numpy 코드를 작성하라.

(b) 행렬 $A$가 직교행렬(orthogonal matrix)임을 이용해 주어진 선형시스템의 해 $\mathbf{x}$를 구하는 numpy 코드를 작성하라. 


In [ ]:
# [정답 작성란: 코드 셀을 추가로 만들어도 무방합니다.]
import numpy as np
import numpy.linalg 

A = np.array([[1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1], [1,1,-1,1,-1,-1,-1,1,1,1,-1,1], [1, 1, 1,-1,1,-1,-1,-1,1,1,1,-1],[1,-1,1,1,-1,1,-1,-1,-1,1,1,1],[1,1,-1,1,1,-1,1,-1,-1,-1,1,1],[1,1,1,-1,1,1,-1,1,-1,-1,-1,1],[1,1,1,1,-1,1,1,-1,1,-1,-1,-1],[1,-1,1,1,1,-1,1,1,-1,1,-1,-1],[1,-1,-1,1,1,1,-1,1,1,-1,1,-1],[1,-1,-1,-1,1,1,1,-1,1,1,-1,1],[1,1,-1,-1,-1,1,1,1,-1,1,1,-1],[1,-1,1,-1,-1,-1,1,1,1,-1,1,1]])
print(A)

Q, R = np.linalg.qr(A)

print("Q:", Q)
print("R:", R)

b=np.array([-33,-5,19,-5,-9,7,11,9,5,11,-23,13])
print(b)

y = Q.T @ b

print("y:", y)

x = np.linalg.inv(R) @ y

print("x:", x)
print(np.shape(x))

if np.allclose(A@x, b):
  print("Ok")
else:
  print("something wrong")

[[ 1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [ 1  1 -1  1 -1 -1 -1  1  1  1 -1  1]
 [ 1  1  1 -1  1 -1 -1 -1  1  1  1 -1]
 [ 1 -1  1  1 -1  1 -1 -1 -1  1  1  1]
 [ 1  1 -1  1  1 -1  1 -1 -1 -1  1  1]
 [ 1  1  1 -1  1  1 -1  1 -1 -1 -1  1]
 [ 1  1  1  1 -1  1  1 -1  1 -1 -1 -1]
 [ 1 -1  1  1  1 -1  1  1 -1  1 -1 -1]
 [ 1 -1 -1  1  1  1 -1  1  1 -1  1 -1]
 [ 1 -1 -1 -1  1  1  1 -1  1  1 -1  1]
 [ 1  1 -1 -1 -1  1  1  1 -1  1  1 -1]
 [ 1 -1  1 -1 -1 -1  1  1  1 -1  1  1]]
Q: [[-0.28867513  0.28867513  0.28867513  0.28867513  0.28867513  0.28867513
   0.28867513  0.28867513  0.28867513  0.28867513  0.28867513 -0.28867513]
 [-0.28867513 -0.28867513  0.28867513 -0.28867513  0.28867513  0.28867513
   0.28867513 -0.28867513 -0.28867513 -0.28867513  0.28867513  0.28867513]
 [-0.28867513 -0.28867513 -0.28867513  0.28867513 -0.28867513  0.28867513
   0.28867513  0.28867513 -0.28867513 -0.28867513 -0.28867513 -0.28867513]
 [-0.28867513  0.28867513 -0.28867513 -0.28867513  0.28867513 -0.28867513
   0.28

# 문제 4)
네 개의 점 $(-3,3)$, $(-2,3)$, $(-1,2)$, $(0,0)$이 있을 때, 이들을  근사(approximation)하는 직선의 방정식 $y = mx + c$을 최소제곱법(least squares method)으로 구하는 코드를 작성하시오.  

In [ ]:
# [정답 작성란: 코드 셀을 추가로 만들어도 무방합니다.]
import numpy as np
import numpy.linalg

A= np.array([[-3,3],[-2,3],[-1,2],[0,0]])
b= np.array([3,3,2,0])

print(A)
print(b)

x_opt = np.linalg.lstsq(A, b, rcond=None)[0]

print(x_opt)

if np.allclose(A @ x_opt, b):
  print("Ok")
else:
  print("something wrong")

[[-3  3]
 [-2  3]
 [-1  2]
 [ 0  0]]
[3 3 2 0]
[-5.20833879e-16  1.00000000e+00]
Ok
